# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoFeeds' do
  # Comment the next line if you don't want to use dynamic frameworks
pod 'Swinject'
pod 'SnapKit', '~> 5.7.0'
pod 'Texture'
  use_frameworks!

  # Pods for VideoFeeds

  target 'VideoFeedsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoFeedsUITests' do
    # Pods for testing
  end

end
